name: Test Python app

on:
  push:
    branches:
      - main
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install tkinter
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk
    - name: Run unittest tests
      run: |
        python -m unittest test_calculator_unittest.py -v
    - name: Run pytest tests
      run: |
        pytest --cov=calculator -v
